### ISSUE TITLE
Three TCK tests are missing annotation literals in their deployments

### ISSUE THREAD

**Issue by manovotn** [jakartaee/cdi-tck#493]
This is a regression caused by https://github.com/jakartaee/cdi-tck/commit/dcdbe5a1af37d73ddd70effe35138a5bb7d1dc06 for the 4.1 version.

The commit correctly introduced several new `Literals` and introduced there usage but forgot to add them in respective test deployments. These are as follows:
* `ResolveEventObserversTest`
* `AlternativeMetadataTest`
* `BeanManagerTest`

This then leads to a `NoClassDefFoundError`.
I'll send a PR once I double check this doesn't appear anywhere else; I'll also issue a new 4.1 Alpha so that we have a version that's correctly testable.
